force-app/main/default/objects/RC_student_test__c/RC_student_test__c.object-meta.xml
<CustomObject>
    <label>RC_student_test</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Student Test</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Tests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_student_test__c/fields/code_warnings__c.field-meta.xml
<CustomField>
    <fullName>code_warnings__c</fullName>
    <defaultValue>15</defaultValue>
    <description>Displays the number of warning for the code page</description>
    <label>code_warnings</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/fields/event_id__c.field-meta.xml
<CustomField>
    <fullName>event_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>event_id</label>
    <referenceTo>RC_event__c</referenceTo>
    <relationshipLabel>RC_student_tests</relationshipLabel>
    <relationshipName>RC_student_tests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/fields/student_id__c.field-meta.xml
<CustomField>
    <fullName>student_id__c</fullName>
    <label>student_id</label>
    <referenceTo>RC_student__c</referenceTo>
    <relationshipLabel>RC_student_tests</relationshipLabel>
    <relationshipName>RC_student_tests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/default/classes/CodePageController.cls
public with sharing class CodePageController {
    public CodePageController() {

    }

    @RemoteAction
   public static  RC_student_test__c GetCurrentStudentSession(Id studentId,Id eventId ) {  
      RC_student_test__c codeWarnings = [SELECT Id, code_warnings__c FROM RC_student_test__c  WHERE student_id__c = :studentId and event_id__c = :eventId];
      return codeWarnings;
   }

    @RemoteAction
   public static void UpdateCodeWarnings(Integer codeWarnings, String EventID, String studentID) {  
      RC_student_test__c currentTimeDB = [SELECT Id, code_warnings__c FROM RC_student_test__c  WHERE student_id__c = :studentId and event_id__c = :eventId];
      currentTimeDB.code_warnings__c = codeWarnings;
      update currentTimeDB;
   }
}