force-app/main/default/objects/RC_college__c/RC_college__c.object-meta.xml
<CustomObject>
    <label>RC_college</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_student__c/RC_student__c.object-meta.xml
<CustomObject>
    <label>RC_student</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_student__c/fields/branch_type__c.field-meta.xml
<CustomField>
    <fullName>branch_type__c</fullName>
    <label>branch_type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/city__c.field-meta.xml
<CustomField>
    <fullName>city__c</fullName>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/college_id__c.field-meta.xml
<CustomField>
    <fullName>college_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>college_id</label>
    <referenceTo>RC_college__c</referenceTo>
    <relationshipLabel>RC_students</relationshipLabel>
    <relationshipName>RC_students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/degree_cgpa__c.field-meta.xml
<CustomField>
    <fullName>degree_cgpa__c</fullName>
    <label>Degree_CGPA</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/degree_pass_year__c.field-meta.xml
<CustomField>
    <fullName>degree_pass_year__c</fullName>
    <label>Degree Pass Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/degree_pursuing__c.field-meta.xml
<CustomField>
    <fullName>degree_pursuing__c</fullName>
    <label>Degree Pursuing</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/diploma_college_name__c.field-meta.xml
<CustomField>
    <fullName>diploma_college_name__c</fullName>
    <label>Diploma College Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/diploma_marks__c.field-meta.xml
<CustomField>
    <fullName>diploma_marks__c</fullName>
    <label>Diploma Marks</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/diploma_passing_year__c.field-meta.xml
<CustomField>
    <fullName>diploma_passing_year__c</fullName>
    <label>Diploma Passing Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/hsc_marks__c.field-meta.xml
<CustomField>
    <fullName>hsc_marks__c</fullName>
    <label>High School (CGPA/Percentage)</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/hsc_name__c.field-meta.xml
<CustomField>
    <fullName>hsc_name__c</fullName>
    <label>High School (10th Grade) Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/hsc_pass_year__c.field-meta.xml
<CustomField>
    <fullName>hsc_pass_year__c</fullName>
    <label>High School Pass Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/isHired__c.field-meta.xml
<CustomField>
    <fullName>isHired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hiring Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/phone__c.field-meta.xml
<CustomField>
    <fullName>phone__c</fullName>
    <inlineHelpText>Please add Phone/Mobile Number</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/pincode__c.field-meta.xml
<CustomField>
    <fullName>pincode__c</fullName>
    <label>Pincode</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/ssc_marks__c.field-meta.xml
<CustomField>
    <fullName>ssc_marks__c</fullName>
    <label>Secondary School (CGPA/Percentage)</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/ssc_name__c.field-meta.xml
<CustomField>
    <fullName>ssc_name__c</fullName>
    <label>Secondary School Name (12th Grade)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/ssc_pass_year__c.field-meta.xml
<CustomField>
    <fullName>ssc_pass_year__c</fullName>
    <label>Secondary School Pass Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/state__c.field-meta.xml
<CustomField>
    <fullName>state__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>Odisha</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>Uttarakhand</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
            <value>
                <fullName>West Bengal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/street__c.field-meta.xml
<CustomField>
    <fullName>street__c</fullName>
    <label>Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/usn__c.field-meta.xml
<CustomField>
    <fullName>usn__c</fullName>
    <label>USN</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/studentProfileController.cls
public with sharing class studentProfileController {
    public studentProfileController() {

    }
    @RemoteAction
    public static Map<String, Object> retriveStudentDetails(String studentId){
        Map<String, Object> result = new Map<String, Object>();
        
        try {
            RC_student__c student = [SELECT Id, Name, branch_type__c, city__c, college_id__r.Name, diploma_college_name__c, 
                                            diploma_passing_year__c, email__c, hsc_marks__c, hsc_name__c, phone__c, 
                                            hsc_pass_year__c, pincode__c, ssc_marks__c, ssc_name__c, ssc_pass_year__c, 
                                            state__c, street__c, usn__c, isHired__c, diploma_marks__c, 
                                            degree_pursuing__c, degree_cgpa__c, degree_pass_year__c 
                                      FROM RC_student__c 
                                      WHERE Id = :studentId];
            result.put('Id', student.Id);
            result.put('Name', student.Name);
            result.put('branch_type__c', student.branch_type__c);
            result.put('city__c', student.city__c);
            result.put('college_id__c', student.college_id__r.Name);
            result.put('diploma_college_name__c', student.diploma_college_name__c);
            result.put('diploma_passing_year__c', student.diploma_passing_year__c);
            result.put('email__c', student.email__c);
            result.put('hsc_marks__c', student.hsc_marks__c);
            result.put('hsc_name__c', student.hsc_name__c);
            result.put('phone__c', student.phone__c);
            result.put('hsc_pass_year__c', student.hsc_pass_year__c);
            result.put('pincode__c', student.pincode__c);
            result.put('ssc_marks__c', student.ssc_marks__c);
            result.put('ssc_name__c', student.ssc_name__c);
            result.put('ssc_pass_year__c', student.ssc_pass_year__c);
            result.put('state__c', student.state__c);
            result.put('street__c', student.street__c);
            result.put('usn__c', student.usn__c);
            result.put('isHired__c', student.isHired__c);
            result.put('diploma_marks__c', student.diploma_marks__c);
            result.put('degree_pursuing__c', student.degree_pursuing__c);
            result.put('degree_cgpa__c', student.degree_cgpa__c);
            result.put('degree_pass_year__c', student.degree_pass_year__c);
            
            result.put('success', true);
        } catch (Exception e) {
            result.put('success', false);
            result.put('errorMessage', e.getMessage());
        }
        
        return result;
    }
    
}