force-app/main/default/objects/RC_college__c/RC_college__c.object-meta.xml
<CustomObject>
    <label>RC_college</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_student__c/RC_student__c.object-meta.xml
<CustomObject>
    <label>RC_student</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_student__c/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/usn__c.field-meta.xml
<CustomField>
    <fullName>usn__c</fullName>
    <label>USN</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/studentRegistrationController.cls
public without sharing class studentRegistrationController {
    public studentRegistrationController() {

    }

    @RemoteAction
    public static RC_student__c createStudentBasicAccount(
        String name, 
        String phone, 
        String email, 
        String address1,
        // String address2, 
        String usn, 
        String city, 
        String state, 
        String pincode,
        String collegeId,
        String schoolName, 
        Decimal schoolMarks, 
        String schoolPassYear, 
        String secondarySchoolName, 
        Decimal puMarks, 
        String puPassingYear,
        String degreeType,
        String branchType,
        Decimal degreeMarks, 
        String degreePassingYear) 
    {
        return DML.getInstance().createStudentBasicAccount(name, phone, email, address1, usn, city, state, pincode,collegeId, schoolName, schoolMarks, schoolPassYear, secondarySchoolName, puMarks, puPassingYear, degreeType, branchType, degreeMarks, degreePassingYear);
    }

    @RemoteAction
    public static List<RC_college__c> getAllCollegeNames()
    {
        List<RC_college__c> collegeNames = [Select Name from RC_college__c];
        return collegeNames;
    }

    @RemoteAction
    public static Boolean checkIfUsnAndEmailExist(String usn, String email) {
        Boolean usnExists = [SELECT COUNT() FROM RC_student__c WHERE usn__c = :usn] > 0;
        Boolean emailExists = [SELECT COUNT() FROM RC_student__c WHERE email__c = :email] > 0;
        
        return (usnExists || emailExists);
    }

}