force-app/main/default/objects/RC_college__c/RC_college__c.object-meta.xml
<CustomObject>
    <label>RC_college</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_event__c/RC_event__c.object-meta.xml
<CustomObject>
    <description>An event refers to a placement drive ina  campus which can have even a pooled campus drive.</description>
    <label>RC_event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_event__c/fields/event_date__c.field-meta.xml
<CustomField>
    <fullName>event_date__c</fullName>
    <label>Event_date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RC_event__c/fields/event_id__c.field-meta.xml
<CustomField>
    <fullName>event_id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>As credentials similar to an event password</description>
    <label>event id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RC_event__c/fields/event_start_time__c.field-meta.xml
<CustomField>
    <fullName>event_start_time__c</fullName>
    <label>Event_start_time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/RC_question_set__c/RC_question_set__c.object-meta.xml
<CustomObject>
    <label>RC_question_set</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>RC_Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RC_question_sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_question_set__c/fields/option_2__c.field-meta.xml
<CustomField>
    <fullName>option_2__c</fullName>
    <label>option 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_question_set__c/fields/option_3__c.field-meta.xml
<CustomField>
    <fullName>option_3__c</fullName>
    <label>option 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_question_set__c/fields/question_category__c.field-meta.xml
<CustomField>
    <fullName>question_category__c</fullName>
    <label>question_category</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_question_set__c/fields/question_description__c.field-meta.xml
<CustomField>
    <fullName>question_description__c</fullName>
    <label>question_description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RC_question_set__c/fields/question_difficulty__c.field-meta.xml
<CustomField>
    <fullName>question_difficulty__c</fullName>
    <label>question_difficulty</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_question_set__c/fields/question_title__c.field-meta.xml
<CustomField>
    <fullName>question_title__c</fullName>
    <label>question_title</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RC_student__c/RC_student__c.object-meta.xml
<CustomObject>
    <label>RC_student</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_student__c/fields/college_id__c.field-meta.xml
<CustomField>
    <fullName>college_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>college_id</label>
    <referenceTo>RC_college__c</referenceTo>
    <relationshipLabel>RC_students</relationshipLabel>
    <relationshipName>RC_students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/RC_student_question__c/RC_student_question__c.object-meta.xml
<CustomObject>
    <label>RC_student_question</label>
    <nameField>
        <label>RC_student_question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RC_student_questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_student_question__c/fields/hasProgram__c.field-meta.xml
<CustomField>
    <fullName>hasProgram__c</fullName>
    <defaultValue>false</defaultValue>
    <label>hasProgram</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RC_student_question__c/fields/option_1__c.field-meta.xml
<CustomField>
    <fullName>option_1__c</fullName>
    <label>option 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_student_question__c/fields/option_2__c.field-meta.xml
<CustomField>
    <fullName>option_2__c</fullName>
    <label>option 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_student_question__c/fields/option_3__c.field-meta.xml
<CustomField>
    <fullName>option_3__c</fullName>
    <label>option 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_student_question__c/fields/option_4__c.field-meta.xml
<CustomField>
    <fullName>option_4__c</fullName>
    <label>option 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_student_question__c/fields/question_category__c.field-meta.xml
<CustomField>
    <fullName>question_category__c</fullName>
    <label>question_category</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_student_question__c/fields/question_correct_answer__c.field-meta.xml
<CustomField>
    <fullName>question_correct_answer__c</fullName>
    <label>question_correct_answer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_student_question__c/fields/question_description__c.field-meta.xml
<CustomField>
    <fullName>question_description__c</fullName>
    <label>question_description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RC_student_question__c/fields/question_difficulty__c.field-meta.xml
<CustomField>
    <fullName>question_difficulty__c</fullName>
    <label>question_difficulty</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_student_question__c/fields/question_title__c.field-meta.xml
<CustomField>
    <fullName>question_title__c</fullName>
    <label>question_title</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/RC_student_test__c.object-meta.xml
<CustomObject>
    <label>RC_student_test</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Student Test</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Tests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_student_test__c/fields/event_id__c.field-meta.xml
<CustomField>
    <fullName>event_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>event_id</label>
    <referenceTo>RC_event__c</referenceTo>
    <relationshipLabel>RC_student_tests</relationshipLabel>
    <relationshipName>RC_student_tests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/fields/isLoggedIn__c.field-meta.xml
<CustomField>
    <fullName>isLoggedIn__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To check if the candidate is logged in or not</description>
    <label>isLoggedIn</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/fields/student_id__c.field-meta.xml
<CustomField>
    <fullName>student_id__c</fullName>
    <label>student_id</label>
    <referenceTo>RC_student__c</referenceTo>
    <relationshipLabel>RC_student_tests</relationshipLabel>
    <relationshipName>RC_student_tests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Testing.cls
public class Testing 
{
    public static void TestC()
    {
         List<RC_college__c> colleges = [SELECT Id FROM RC_college__C];
		system.debug(colleges);
        
        List<RC_student__c> students = [SELECT Id, college_id__C FROM RC_student__C];
        system.debug(students);
        
        Integer j = 0;
        for(Integer i = 0; i < students.size(); i++)
        {
            students[i].college_id__c = colleges[j].Id;
            
            if(math.mod(i, 40) == 0)
            {
                system.debug(j);
                
                if(j < colleges.size()-1) j++;
                
            }	
            
            system.debug(students[i].college_id__c);
        }
        
        update students;
    }
    
    public static void AddCorrectAnswertToQuestions()
    {
        List<RC_student_question__c> questionsFortheStudent = [Select Id FROM RC_student_question__c];
        String[] opts = new String[]{'option_1','option_2','option_3','option_4'};
        
        for(Integer i =0; i < questionsForTheStudent.size(); i++)
        {
            Integer IntrandomNumber = Integer.valueof((Math.random() * 4));
            questionsFortheStudent[i].question_correct_answer__c = opts[IntrandomNumber];
            System.debug(opts[IntrandomNumber]);
        }
        
        update questionsFortheStudent;
        
    }
    
    public static void GetRandomQuestions()
    {
        Integer aptiSize = 5, cProgrammingSize = 5; 
        List<RC_question_set__c> questionsForStudent = new List<RC_question_set__c>();
        List<RC_question_set__c> aptitudeQuestions = new List<RC_question_set__c>();
        List<RC_question_set__c> cProgrammingQuestions = new List<RC_question_set__c>();
        
        List<RC_question_set__c> allQuestions = [SELECT Id,question_category__c FROM RC_question_set__c];
        
        for(Integer i = 0; i < allQuestions.size(); i++)
        {
            if(allQuestions[i].question_category__c == 'Aptitude')
            {
                aptitudeQuestions.add(allQuestions[i]);
            }
            else
            {
                cProgrammingQuestions.add(allQuestions[i]);
            }
        }
        
        List<Integer> questionSizeIndex = PopulateQuestionIndex(aptitudeQuestions.size());
        List<Integer> chosenQuestionIndex = new List<Integer>();
        
        
        
        
        //get apti set
        while(aptiSize > 0)
        {
            Integer index = Integer.valueof((Math.random() * questionSizeIndex.size()));
            chosenQuestionIndex.add(questionSizeIndex[index]);
            questionSizeIndex.remove(index);
            aptiSize--;
        }
        
        System.debug(chosenQuestionIndex);
        
        for(Integer i = 0 ; i < chosenQuestionIndex.size(); i++)
        {
            questionsForStudent.add(aptitudeQuestions[chosenQuestionIndex[i]]);
        }
        
        chosenQuestionIndex.clear();
        
        //get CQuestions set
        questionSizeIndex.clear();
        questionSizeIndex = PopulateQuestionIndex(cProgrammingQuestions.size());
        
        while(cProgrammingSize > 0)
        {
            Integer index = Integer.valueof((Math.random() * questionSizeIndex.size()));
            chosenQuestionIndex.add(questionSizeIndex[index]);
            questionSizeIndex.remove(index);
            cProgrammingSize--;
        }
        
        System.debug(chosenQuestionIndex);
        
        for(Integer i = 0 ; i < chosenQuestionIndex.size(); i++)
        {
            questionsForStudent.add(cProgrammingQuestions[chosenQuestionIndex[i]]);
        }
        
        
        //iterate and display all questions
        for(Integer i =0 ; i < questionsForStudent.size(); i++)
        {
            System.debug(questionsForStudent[i]);
        }
    }
    
    public static List<Integer> PopulateQuestionIndex(Integer size)
    {
         List<Integer> questionIndex = new List<Integer>();
        for(Integer i = 0; i < size; i++)
        {
            questionIndex.add(i);
        }
        
        return questionIndex;
    }
    
    public static void testFn(){
        Time  eventTime = [SELECT Id, event_start_time__c FROM RC_event__c WHERE Id = 'a025j00000d4iX0AAI'].event_start_time__c;
        System.debug(eventTime);
             Integer hours = eventTime.hour();
                Integer minutes = eventTime.minute();
                Integer seconds = eventTime.second();
                
                // Format the time as HH:mm:ss
                String formattedHours = String.valueOf(hours).leftPad(2, '0');
                String formattedMinutes = String.valueOf(minutes).leftPad(2, '0');
                String formattedSeconds = String.valueOf(seconds).leftPad(2, '0');
                
                String formattedTime = formattedHours + ':' + formattedMinutes + ':' + formattedSeconds;
                
                System.debug(formattedTime);
    }
    
    public static void GetEventsFromPassword(String password)
    {
        List<RC_event__c> events = [SELECT Id, event_id__c from RC_event__c where event_id__c = :password];
        
        System.debug('No of Events: ' + events.size());
    }
    
    public static void DeleteAllQuestionFromQuestionSet()
    {
        List<RC_question_set__c> question = [SELECT Id from RC_question_set__c];
        
        delete question;
    }
    
    public static void GetStudentTestIdFromEventAndStudent()
    {
        Id eventID = 'a025j00000eXLqaAAB';
        Id StudentId ='a055j00000WiqWZAAZ';
        RC_student_test__c studentTest;

        try{
        	 studentTest = [Select Id, isLoggedIn__c From RC_student_test__c where student_id__c = :StudentId and event_id__c = :eventID];
        	}
        catch(Exception ex){
            studentTest = null;
        }
        System.debug(studentTest);
    }
    
    public static void CheckDate()
    {
        DateTime todaysDate = System.today();
String todaysDateStr = todaysDate.format('yyyy-MM-dd');
System.debug(todaysDateStr);
    }
    
    public static void TestQuery()
    {
        String EmailInput = 'adi@mail.com';
        String eventPassword = 'sept12';
         System.debug('email and pass '+EmailInput+' '+eventPassword);
        
       List<RC_event__c> eventRes = [SELECT Id, event_id__c, event_date__c FROM RC_event__c where event_id__c = :eventPassword];
       List<RC_student__c> studentRes = [SELECT Id, email__c FROM RC_student__c where email__c = :EmailInput];
       System.debug('eventRes ' +eventRes);
       System.debug('studentRes '+studentRes);
    }
    
    public static void Jsontestt()
    {        
       	List<RC_question_set__c> questions = [SELECT Id, Name, hasProgram__c, question_correct_answer__c, question_description__c, question_title__c, option_1__c, option_2__c, option_3__c, option_4__c, question_category__c, question_difficulty__c FROM RC_question_set__c];
        
        Map<string,string> obj = new Map<string,string>();
        obj.put('Id', questions[0].Id);
            obj.put('Name', questions[0].Name);
            obj.put('hasProgram__c', String.valueOf(questions[0].hasProgram__c));
            obj.put('question_correct_answer__c', questions[0].question_correct_answer__c);
            obj.put('question_description__c', questions[0].question_description__c);
            obj.put('question_title__c', questions[0].question_title__c);
            obj.put('option_1__c', questions[0].option_1__c);
            obj.put('option_2__c', questions[0].option_2__c);
            obj.put('option_3__c', questions[0].option_3__c);
            obj.put('option_4__c', questions[0].option_4__c);
            obj.put('question_category__c', questions[0].question_category__c);
            obj.put('question_difficulty__c', questions[0].question_difficulty__c);
        
        RC_question_set__c q = (RC_question_set__c)JSON.deserialize((String)JSON.serialize(obj), RC_question_set__c.class);
        system.Debug(q.Id);
    }
    
    public static void JsonTest()
    {
        string query='SELECT Id, Name, hasProgram__c, question_correct_answer__c, question_description__c, question_title__c, option_1__c, option_2__c, option_3__c, option_4__c, question_category__c, question_difficulty__c FROM RC_question_set__c';
        string Outputget= JSON.serialize(database.query(query)); 
        system.debug(Outputget);
        List<RC_question_set__c> q = (List<RC_question_set__c>) JSON.deserialize(Outputget, List<RC_question_set__c>.class);
        system.Debug(q[0].Id);
        system.Debug(q[1].Id);
    }
}