force-app/main/default/objects/RC_college__c/RC_college__c.object-meta.xml
<CustomObject>
    <label>RC_college</label>
    <nameField>
        <label>College Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colleges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_event__c/RC_event__c.object-meta.xml
<CustomObject>
    <description>An event refers to a placement drive ina  campus which can have even a pooled campus drive.</description>
    <label>RC_event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_event__c/fields/event_id__c.field-meta.xml
<CustomField>
    <fullName>event_id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>As credentials similar to an event password</description>
    <label>event id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RC_student__c/RC_student__c.object-meta.xml
<CustomObject>
    <label>RC_student</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_student__c/fields/branch_type__c.field-meta.xml
<CustomField>
    <fullName>branch_type__c</fullName>
    <label>branch_type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/college_id__c.field-meta.xml
<CustomField>
    <fullName>college_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>college_id</label>
    <referenceTo>RC_college__c</referenceTo>
    <relationshipLabel>RC_students</relationshipLabel>
    <relationshipName>RC_students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/degree_cgpa__c.field-meta.xml
<CustomField>
    <fullName>degree_cgpa__c</fullName>
    <label>Degree_CGPA</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/phone__c.field-meta.xml
<CustomField>
    <fullName>phone__c</fullName>
    <inlineHelpText>Please add Phone/Mobile Number</inlineHelpText>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/RC_student__c/fields/usn__c.field-meta.xml
<CustomField>
    <fullName>usn__c</fullName>
    <label>USN</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/RC_student_test__c.object-meta.xml
<CustomObject>
    <label>RC_student_test</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Student Test</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Tests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_student_test__c/fields/event_id__c.field-meta.xml
<CustomField>
    <fullName>event_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>event_id</label>
    <referenceTo>RC_event__c</referenceTo>
    <relationshipLabel>RC_student_tests</relationshipLabel>
    <relationshipName>RC_student_tests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/fields/student_id__c.field-meta.xml
<CustomField>
    <fullName>student_id__c</fullName>
    <label>student_id</label>
    <referenceTo>RC_student__c</referenceTo>
    <relationshipLabel>RC_student_tests</relationshipLabel>
    <relationshipName>RC_student_tests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/StudentTableController.cls
public with sharing class StudentTableController {
    public List<RC_student__c> studentList {get; private set;}
    public List<RC_college__c> collegeList {get; private set;}
    
    public Integer reqRecords { get; set; }
    public String selectedUserFilter {get; set;}
    public String selectedCollegeId { get; set; }
    public String selectedEventId { get; set; } // Add this property for event selection
    public String studentListType {get; set;}

    public Integer pageSize { get; set; }
    public Integer pageNumber { get; set; }
    public Integer totalPages { get; private set; }

    public String searchText { get; set; }

    public StudentTableController() {
        pageSize = 10;
        pageNumber = 1;
        reqRecords = 0;
        updateStudentList();
    }

    public List<SelectOption> getUserFilterOptions(){
        List<SelectOption> filterOptions = new List<SelectOption>();
        filterOptions.add(new SelectOption('noFilterSelected', '------'));
        filterOptions.add(new SelectOption('displayAllStudents', 'View All Students'));
        filterOptions.add(new SelectOption('displayEventStudents', 'Event'));
        filterOptions.add(new SelectOption('displayCollegeStudents', 'College'));

        return filterOptions;
    }

    public List<SelectOption> getSelectOptions(){
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('noCollegeSelected', '------'));
        if (studentListType == 'college') {
            for(RC_college__c college: [SELECT Id, Name FROM RC_college__c]){
                options.add(new SelectOption(college.Id, college.Name));
            }
        }
        if (studentListType == 'event') {
            for(RC_event__c event: [SELECT Id, Name FROM RC_event__c]){
                options.add(new SelectOption(event.Id, event.Name));
            }
        }
        
        return options;
    }

    public void updateUserFilter(){
        if (selectedUserFilter == 'displayAllStudents'){
            studentListType = null;
        }
        if (selectedUserFilter == 'displayEventStudents'){
            studentListType = 'event';
        }
        if (selectedUserFilter == 'displayCollegeStudents'){
            studentListType = 'college';
        }
        updateStudentList();
    }


    public void updateStudentList(){
        if (selectedCollegeId != null) {
            System.debug(selectedCollegeId);
            if (selectedCollegeId == 'displayAllStudents'){
                reqRecords = [SELECT COUNT() FROM RC_student__c];
            }
            else if (studentListType == 'event') {
                if(selectedCollegeId!=null){
                reqRecords = [SELECT COUNT () FROM RC_student_test__c WHERE event_id__c = :selectedCollegeId];}
            }
            else {
                if(selectedCollegeId!=null){
                reqRecords = [SELECT COUNT() FROM RC_student__c WHERE college_id__c = :selectedCollegeId];}
            }
            pageSize = 10;
            totalPages = (reqRecords + pageSize - 1) / pageSize;
            pageNumber = 1;
            updateStudents();
        }
    }

    public Boolean getPrevDisabled() {
        return pageNumber <= 1;
    }
    
    public Boolean getNextDisabled() {
        return pageNumber >= totalPages;
    }
    
    public void first() {
        pageNumber = 1;
        updateStudents();
    }
    
    public void previous() {
        pageNumber--;
        updateStudents();
    }
    
    public void next() {
        pageNumber++;
        updateStudents();

    }
    
    public void last() {
        pageNumber = totalPages;
        updateStudents();
    }

    public Boolean getShowPagination() {
        return reqRecords > 20;
    }

    public List<SelectOption> getPageSizeOptions() {
        List<Integer> pageSizes = new List<Integer>{
            10,
            (Integer)Math.round(0.2 * reqRecords / 10) * 10,
            (Integer)Math.round(0.3 * reqRecords / 10) * 10,
            (Integer)Math.round(0.5 * reqRecords / 10) * 10,
            (Integer)Math.round(0.75 * reqRecords / 10) * 10,
            reqRecords
        };
    
        List<SelectOption> pageSizeOptions = new List<SelectOption>();
        for (Integer size : pageSizes) {
            pageSizeOptions.add(new SelectOption(String.valueOf(size), String.valueOf(size)));
        }
        return pageSizeOptions;
    }

    public void updateStudents(){
        Integer offset = (pageNumber - 1) * pageSize;

        if (selectedUserFilter == 'displayAllStudents'){
            studentList = [SELECT Id, Name, usn__c, college_id__r.Name , email__c, phone__c, branch_type__c, degree_cgpa__c FROM RC_student__c LIMIT :pageSize OFFSET :offset];
        }
        else if (studentListType == 'event') {
            studentList = [SELECT Id, Name, usn__c, college_id__r.Name , email__c, phone__c, branch_type__c, degree_cgpa__c FROM RC_student__c WHERE Id IN (SELECT student_id__c FROM RC_student_test__c WHERE event_id__c = :selectedCollegeId ) LIMIT :pageSize OFFSET :offset];
        }
        else if (studentListType == 'college') {
            studentList = [SELECT Id, Name, usn__c, college_id__r.Name , email__c, phone__c, branch_type__c, degree_cgpa__c FROM RC_student__c WHERE college_id__c = :selectedCollegeId LIMIT :pageSize OFFSET :offset];
        }
        totalPages = (reqRecords + pageSize - 1) / pageSize;
    }

    public PageReference changePageSizeAction() {
        // Update the page size and reset to the first page
        pageNumber = 1;
        updateStudents();
        return null; // To prevent any navigation
    }
}