force-app/main/default/objects/RC_student_question__c/RC_student_question__c.object-meta.xml
<CustomObject>
    <label>RC_student_question</label>
    <nameField>
        <label>RC_student_question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RC_student_questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_student_question__c/fields/isStudentAnswerdCorrect__c.field-meta.xml
<CustomField>
    <fullName>isStudentAnswerdCorrect__c</fullName>
    <formula>question_correct_answer__c ==  student_attempt__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isStudentAnswerdCorrect</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RC_student_question__c/fields/student_test_id__c.field-meta.xml
<CustomField>
    <fullName>student_test_id__c</fullName>
    <label>student_test_id</label>
    <referenceTo>RC_student_test__c</referenceTo>
    <relationshipName>RC_student_question_sets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/RC_student_test__c.object-meta.xml
<CustomObject>
    <label>RC_student_test</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Student Test</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Tests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_student_test__c/fields/event_id__c.field-meta.xml
<CustomField>
    <fullName>event_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>event_id</label>
    <referenceTo>RC_event__c</referenceTo>
    <relationshipLabel>RC_student_tests</relationshipLabel>
    <relationshipName>RC_student_tests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/fields/student_id__c.field-meta.xml
<CustomField>
    <fullName>student_id__c</fullName>
    <label>student_id</label>
    <referenceTo>RC_student__c</referenceTo>
    <relationshipLabel>RC_student_tests</relationshipLabel>
    <relationshipName>RC_student_tests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/fields/student_test_current_time__c.field-meta.xml
<CustomField>
    <fullName>student_test_current_time__c</fullName>
    <label>student_test_current_time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/fields/student_test_warning__c.field-meta.xml
<CustomField>
    <fullName>student_test_warning__c</fullName>
    <defaultValue>6</defaultValue>
    <label>student_test_warning</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestSubmitScreenCls.cls
public without sharing class TestSubmitScreenCls { 


    public TestSubmitScreenCls() {

    } 
    
    
    //SELECT count(Id) FROM RC_student_question__c where isStudentAnswerdCorrect__c = true and student_test_id__c = 'a075j00000A2W68AAF'
   
 
  

    @RemoteAction
    public static List<RC_student_test__c> GetStudentSubmitStatus(Id studentId,Id eventId) {
          List<RC_student_test__c> studentTestIDRecord =  [SELECT Id, student_test_warning__c, student_test_current_time__c FROM RC_student_test__c where student_id__c = :studentId and event_id__c = :eventId];
          if(studentTestIDRecord.size() != 0){
            return studentTestIDRecord;
          }
          return null;

    }
 
}