force-app/main/default/objects/RC_event__c/RC_event__c.object-meta.xml
<CustomObject>
    <description>An event refers to a placement drive ina  campus which can have even a pooled campus drive.</description>
    <label>RC_event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_event__c/fields/event_id__c.field-meta.xml
<CustomField>
    <fullName>event_id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>As credentials similar to an event password</description>
    <label>event id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RC_student_test__c/RC_student_test__c.object-meta.xml
<CustomObject>
    <label>RC_student_test</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Student Test</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Tests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_student_test__c/fields/event_id__c.field-meta.xml
<CustomField>
    <fullName>event_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>event_id</label>
    <referenceTo>RC_event__c</referenceTo>
    <relationshipLabel>RC_student_tests</relationshipLabel>
    <relationshipName>RC_student_tests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/fields/student_id__c.field-meta.xml
<CustomField>
    <fullName>student_id__c</fullName>
    <label>student_id</label>
    <referenceTo>RC_student__c</referenceTo>
    <relationshipLabel>RC_student_tests</relationshipLabel>
    <relationshipName>RC_student_tests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/autoEventSubmitCtrl.cls
public with sharing class autoEventSubmitCtrl {

    public autoEventSubmitCtrl() {
    }

    @RemoteAction
    public static List<RC_Event__C> retrieveEvents(){
        List<RC_Event__C> eventList=[select Name,id from RC_Event__C];

        return eventList;
    }

    @RemoteAction
    public static String compileEventTests(String eventID){
       
        List<RC_student_test__C> a=[SELECT Id FROM RC_student_test__c WHERE event_id__c=:eventID];
        Integer n = (Integer)Math.ceil(a.size());
        
        for(Integer i=0;i<n;i+=20){
            updateTestsFuture(eventID,i);
        }
        return 'Updation Completed';

    }

    @future
    public static void updateTestsFuture(String eventID,Integer i){
        try{
        List<RC_student_test__c > stlist=[SELECT Id, event_id__c, student_id__c FROM RC_student_test__c
        where event_id__c=:eventID order by student_id__c asc limit 20 offset :i ];

       // Integer start = System.Now().millisecond();
      //  while(System.Now().millisecond()< start+1000){ 
      //  }
        
        for(RC_student_test__c r:stlist)
            {
            AltQuestionPageCtrl.updateTestMarks(r.student_id__c,r.event_id__c );
             }
          
        }catch(Exception e){
            System.debug('compileEventTests exception : '+e);
            System.debug('Exception in compileEventTests');
        }
       System.debug('compileEventTests Succesfully');
     }
    
}