force-app/main/default/objects/RC_event__c/RC_event__c.object-meta.xml
<CustomObject>
    <description>An event refers to a placement drive ina  campus which can have even a pooled campus drive.</description>
    <label>RC_event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_event__c/fields/event_id__c.field-meta.xml
<CustomField>
    <fullName>event_id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>As credentials similar to an event password</description>
    <label>event id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RC_event__c/fields/event_start_time__c.field-meta.xml
<CustomField>
    <fullName>event_start_time__c</fullName>
    <label>Event_start_time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/RC_student_test__c.object-meta.xml
<CustomObject>
    <label>RC_student_test</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Student Test</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Tests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_student_test__c/fields/event_id__c.field-meta.xml
<CustomField>
    <fullName>event_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>event_id</label>
    <referenceTo>RC_event__c</referenceTo>
    <relationshipLabel>RC_student_tests</relationshipLabel>
    <relationshipName>RC_student_tests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/fields/student_id__c.field-meta.xml
<CustomField>
    <fullName>student_id__c</fullName>
    <label>student_id</label>
    <referenceTo>RC_student__c</referenceTo>
    <relationshipLabel>RC_student_tests</relationshipLabel>
    <relationshipName>RC_student_tests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/fields/student_test_current_time__c.field-meta.xml
<CustomField>
    <fullName>student_test_current_time__c</fullName>
    <label>student_test_current_time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/fields/student_test_duration__c.field-meta.xml
<CustomField>
    <fullName>student_test_duration__c</fullName>
    <label>student_test_duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InstructionsPageController.cls
public class InstructionsPageController 
{
   
   @RemoteAction
   public static Integer GetCurrentTimer(Id studentId , Id eventId ) {  
      Decimal currentTime = [SELECT Id, student_id__c, student_test_current_time__c, student_test_duration__c FROM RC_student_test__c  where student_id__c = :studentId and event_id__c = :eventId].student_test_current_time__c;
      return (Integer)currentTime;
   }

   @RemoteAction
   public static String GetTestStartTime( Id eventId){
      Time  eventTime = [SELECT Id, event_start_time__c FROM RC_event__c WHERE Id = :eventId].event_start_time__c;
      System.debug(eventTime);
           Integer hours = eventTime.hour();
              Integer minutes = eventTime.minute();
              Integer seconds = eventTime.second();


            //   return (hours+minutes+seconds);
            //   Format the time as HH:mm:ss
              String formattedHours = String.valueOf(hours).leftPad(2, '0');
              String formattedMinutes = String.valueOf(minutes).leftPad(2, '0');
              String formattedSeconds = String.valueOf(seconds).leftPad(2, '0');
              
              String formattedTime = formattedHours + ':' + formattedMinutes + ':' + formattedSeconds;
              
              System.debug(formattedTime);
              return formattedTime;
   }
}