force-app/main/default/objects/RC_event__c/RC_event__c.object-meta.xml
<CustomObject>
    <description>An event refers to a placement drive ina  campus which can have even a pooled campus drive.</description>
    <label>RC_event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_event__c/fields/event_date__c.field-meta.xml
<CustomField>
    <fullName>event_date__c</fullName>
    <label>Event_date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RC_event__c/fields/event_id__c.field-meta.xml
<CustomField>
    <fullName>event_id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>As credentials similar to an event password</description>
    <label>event id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RC_student__c/RC_student__c.object-meta.xml
<CustomObject>
    <label>RC_student</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_student_test__c/RC_student_test__c.object-meta.xml
<CustomObject>
    <label>RC_student_test</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Student Test</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Tests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_student_test__c/fields/event_id__c.field-meta.xml
<CustomField>
    <fullName>event_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>event_id</label>
    <referenceTo>RC_event__c</referenceTo>
    <relationshipLabel>RC_student_tests</relationshipLabel>
    <relationshipName>RC_student_tests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/fields/has_cleared_cutoff__c.field-meta.xml
<CustomField>
    <fullName>has_cleared_cutoff__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The student has cleared the cutoff for test round.</description>
    <label>hasClearedCutoff</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/fields/neg_student_apti_marks__c.field-meta.xml
<CustomField>
    <fullName>neg_student_apti_marks__c</fullName>
    <label>neg_student_apti_marks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/fields/neg_student_cprogram_marks__c.field-meta.xml
<CustomField>
    <fullName>neg_student_cprogram_marks__c</fullName>
    <label>neg_student_cprogram_marks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/fields/neg_student_marks_scored__c.field-meta.xml
<CustomField>
    <fullName>neg_student_marks_scored__c</fullName>
    <label>neg_student_marks_scored</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/fields/student_apti_marks__c.field-meta.xml
<CustomField>
    <fullName>student_apti_marks__c</fullName>
    <label>student_apti_marks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/fields/student_cprogram_marks__c.field-meta.xml
<CustomField>
    <fullName>student_cprogram_marks__c</fullName>
    <label>student_cprogram_marks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/fields/student_id__c.field-meta.xml
<CustomField>
    <fullName>student_id__c</fullName>
    <label>student_id</label>
    <referenceTo>RC_student__c</referenceTo>
    <relationshipLabel>RC_student_tests</relationshipLabel>
    <relationshipName>RC_student_tests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RC_student_test__c/fields/student_marks_scored__c.field-meta.xml
<CustomField>
    <fullName>student_marks_scored__c</fullName>
    <label>student_marks_scored</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EventList.cls
public with sharing class EventList {

    public class StudentInfo {
        public String studentName { get; set; }
        public Decimal marksScored { get; set; }
        public Boolean clearedCutoff { get; set; }
        public Decimal cpMarks { get; set; }
        public Decimal aptiMarks { get; set; }
        public Decimal negtotalMarks { get; set; }
        public Decimal negcpMarks { get; set; }
        public Decimal negaptiMarks { get; set; }
        public String Id { get; set; }
    
        public StudentInfo(String fid, String name, Decimal marks, Boolean cleared, Decimal cpm, Decimal aptim, Decimal negtm, Decimal negcpm, Decimal negaptim) {
            studentName = name;
            marksScored = marks;
            clearedCutoff = cleared;
            cpMarks = cpm;
            aptiMarks = aptim;
            negtotalMarks = negtm;
            negcpMarks = negcpm;
            negaptiMarks = negaptim;
            Id = fid;

        }
    }

    public class MyWrapper {
        public List<RC_student__c> student_list { get; set; }
        public List<RC_event__c> Event_List { get; set; }
        public List<RC_student_test__c> student_test_details { get; set; }
        public List<StudentInfo> studentInfoList { get; set; }
    }



    @RemoteAction
    public static MyWrapper showResults(String event_id, Integer check){

        MyWrapper result = new MyWrapper();
        result.studentInfoList = new List<StudentInfo>();


        if (check == 1){
        result.student_test_details = [Select student_id__c, student_marks_scored__c, has_cleared_cutoff__c, student_cprogram_marks__c, student_apti_marks__c, neg_student_marks_scored__c, neg_student_cprogram_marks__c, neg_student_apti_marks__c from RC_student_test__c where event_id__c = :event_id];
        
        
        Set<Id> studentIds = new Set<Id>();
        for (RC_student_test__c junctionRecord : result.student_test_details) {
            studentIds.add(junctionRecord.student_id__c);
        }

        result.student_list = [SELECT Name FROM RC_student__c WHERE Id IN :studentIds];


        Map<Id, String> studentNameMap = new Map<Id, String>();

        // Populate a map of student Ids to student names
        for (RC_student__c student : result.student_list) {
            studentNameMap.put(student.Id, student.Name);
        }


        for (RC_student_test__c junctionRecord : result.student_test_details) {
            String studentName = studentNameMap.get(junctionRecord.student_id__c);
            if (studentName != null) {
                StudentInfo studentInfo = new StudentInfo(junctionRecord.Id, studentName, junctionRecord.student_marks_scored__c, junctionRecord.has_cleared_cutoff__c, junctionRecord.student_cprogram_marks__c, junctionRecord.student_apti_marks__c, junctionRecord.neg_student_marks_scored__c, junctionRecord.neg_student_cprogram_marks__c, junctionRecord.neg_student_apti_marks__c);
                result.studentInfoList.add(studentInfo);
            }
        }


        return result;


    }
    else{
        result.Event_List = [select Name,event_date__c from RC_event__c];
        return result;
    }
}
}