force-app/main/default/objects/RC_question_set__c/RC_question_set__c.object-meta.xml
<CustomObject>
    <label>RC_question_set</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>RC_Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RC_question_sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_question_set__c/fields/option_2__c.field-meta.xml
<CustomField>
    <fullName>option_2__c</fullName>
    <label>option 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_question_set__c/fields/option_3__c.field-meta.xml
<CustomField>
    <fullName>option_3__c</fullName>
    <label>option 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_question_set__c/fields/question_category__c.field-meta.xml
<CustomField>
    <fullName>question_category__c</fullName>
    <label>question_category</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_question_set__c/fields/question_description__c.field-meta.xml
<CustomField>
    <fullName>question_description__c</fullName>
    <label>question_description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RC_question_set__c/fields/question_difficulty__c.field-meta.xml
<CustomField>
    <fullName>question_difficulty__c</fullName>
    <label>question_difficulty</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_question_set__c/fields/question_title__c.field-meta.xml
<CustomField>
    <fullName>question_title__c</fullName>
    <label>question_title</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/default/classes/InsertQuestionSetsctrl.cls
public with sharing class InsertQuestionSetsctrl {
   

    @RemoteAction 
    public static Boolean insertQuestion
    (
        String questionDescription,
        String questionDifficulty,
        String questionTitle,
        String questionCategory,
        String option1,
        String option2,
        String option3,
        String option4,
        String questionCorrectAnswer,
        Boolean hasProgram,
        Boolean isUpdate,
        String qID
    )
    {
        return DML.getInstance().insertQuestionIntoQuestionSet
        (
            questionDescription,
            questionDifficulty,
            questionTitle,
            questionCategory,
            option1,
            option2,
            option3,
            option4,
            questionCorrectAnswer,
            hasProgram,
            isUpdate,
            qID
        );

    }

    
    @RemoteAction
    public static RC_question_set__c getSingleQuestion(String qID){
        List<RC_question_set__c> q = [SELECT question_title__c, Id, hasProgram__c, question_correct_answer__c, question_description__c, option_1__c, option_2__c, option_3__c, option_4__c, question_category__c, question_difficulty__c FROM RC_question_set__c where Id = :qID];
        if(q.size() != 0){
            return q[0];
        }
        return null;
    }
}