force-app/main/default/objects/RC_admin__c/RC_admin__c.object-meta.xml
<CustomObject>
    <description>The admins to this project</description>
    <label>RC_admin</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Admins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_admin__c/fields/adminEmail__c.field-meta.xml
<CustomField>
    <fullName>adminEmail__c</fullName>
    <label>adminEmail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/RC_admin__c/fields/adminPassword__c.field-meta.xml
<CustomField>
    <fullName>adminPassword__c</fullName>
    <label>adminPassword</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/RC_panelist__c/RC_panelist__c.object-meta.xml
<CustomObject>
    <description>Panellists who can chosen for placements drive when creating an event.</description>
    <label>RC_panelist</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>RC_panelist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panelists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_panelist__c/fields/panelistsEmail__c.field-meta.xml
<CustomField>
    <fullName>panelistsEmail__c</fullName>
    <label>panelistsEmail</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RC_panelist__c/fields/panelistsPassword__c.field-meta.xml
<CustomField>
    <fullName>panelistsPassword__c</fullName>
    <label>panelistsPassword</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AdminLoginController.cls
public with sharing class AdminLoginController {
    public class LoginDetails{
        public String recordID;
        public Boolean isAdmin;
        public LoginDetails(String recordID,Boolean isAdmin){
            this.recordID = recordID;
            this.isAdmin = isAdmin;
        }
    }

    @RemoteAction
    public static LoginDetails LoginAdmin(String EmailInput, String adminPassword) {

            List<RC_panelist__c> panelistRes = [SELECT Id, panelistsEmail__c FROM RC_panelist__c WHERE panelistsEmail__c = :EmailInput AND panelistsPassword__c = :adminPassword];
            List<RC_admin__c> adminRes = [SELECT Id, adminEmail__c FROM RC_admin__c WHERE adminEmail__c = :EmailInput AND adminPassword__c = :adminPassword];

            if(adminRes.size() != 0)
            {
                LoginDetails lg = new LoginDetails(adminRes[0].Id,true);
                return lg;
            }

            if(panelistRes.size() != 0)
            {
                LoginDetails lg = new LoginDetails(panelistRes[0].Id,false);
                return lg;
            }

            if(adminRes.size() == 0 && panelistRes.size() == 0)
            {
                LoginDetails lg = new LoginDetails('',false);
                return lg;
            }

            return null;
       }
    
}