force-app/main/default/objects/RC_admin__c/RC_admin__c.object-meta.xml
<CustomObject>
    <description>The admins to this project</description>
    <label>RC_admin</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Admins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RC_admin__c/fields/adminEmail__c.field-meta.xml
<CustomField>
    <fullName>adminEmail__c</fullName>
    <label>adminEmail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/RC_admin__c/fields/adminPassword__c.field-meta.xml
<CustomField>
    <fullName>adminPassword__c</fullName>
    <label>adminPassword</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/default/classes/AdminLoginController.cls
public with sharing class AdminLoginController {
    public class EventStudentDetails{
        public String EventId;
        public String StudentId;
        public String ErrorMsg; 
        public EventStudentDetails(String EventId,String StudentId,String ErrorMsg){
            this.EventId = EventId;
            this.StudentId = StudentId;
            this.ErrorMsg = ErrorMsg;
        }
    }

    @RemoteAction
    public static String LoginAdmin(String EmailInput, String adminPassword) {

            List<RC_admin__c> adminRes = [SELECT Id, adminEmail__c FROM RC_admin__c WHERE adminEmail__c = :EmailInput AND adminPassword__c = :adminPassword];

            if(adminRes.size() == 0)
            {
                return null;
            }

           return adminRes[0].Id;
       }
    
}